configs:
  cm:
    application.resourceTrackingMethod: annotation
server:
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - gitops.34.174.77.152.nip.io
